modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "picaxe"
version = "${version}"
displayName = "PicAxe"
authors = "Jacobwasbeast"
description = '''
Use a Picture Axe to put internet images onto your shields, banners and even your beds.
'''
#logoFile = ""

[[dependencies.picaxe]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.picaxe]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.picaxe]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
