modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "picaxe"
version = "${version}"
displayName = "PicAxe"
authors = "Jacobwasbeast"
description = '''
Use a Picture Axe to put internet images onto your shields, banners and even your beds.
'''
#logoFile = ""

[[dependencies.picaxe]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.picaxe]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.picaxe]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "picaxe.mixins.json"
